export {default as Navbar} from './navbar/Navbar';
export {default as Hero} from './hero/Hero';
export {default as OurStory} from './ourStory/OurStory';
export {default as Services} from './services/Services';
export {default as Offer} from './offer/Offer';
export {default as ReserveTable} from './reserveTable/ReserveTable';
export {default as Recommended} from './recommended/Recommended';
export {default as Menu} from './menu/Menu';
export {default as Blog} from './blog/Blog';